name: Bug
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
